name: teste_app_extrato
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.16.2 <3.0.0"

dependencies:
  change_app_package_name: ^1.0.0
  cupertino_icons: ^1.0.2
  firebase_auth: ^3.3.19
  firebase_core: ^1.17.1
  flutter:
    sdk: flutter
  flutter_launcher_icons: ^0.9.2
  flutter_modular: ^5.0.2
  google_fonts: ^3.0.1
  liquid_swipe: ^2.1.1

dev_dependencies:
  flutter_lints: ^1.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/logo/
    - assets/decoration/

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/logo/logo.png"

scripts:
  cleanner: flutter clean && flutter pub get
  buildrunner: flutter clean && flutter pub get && flutter pub run build_runner
    build --delete-conflicting-outputs
  buildapk: flutter clean && flutter pub get && cd android && flutter build apk
